ip_address: '192.168.1.XXX'  # Replace with the actual IP address of your Xiaomi Smart Home Hub 2
token: 'your_device_token_here'  # Replace with the actual token of your device
model: 'model_identifier'  # Replace with the model identifier of your Xiaomi Smart Home Hub 2, e.g., DMWG03LM (China model), ZNDMWG04LM (Euro model)
